package com.company;

public interface INumberGenerator {
    /**
     * @return the generated number.
     */
    int getSecretNumber();

    /**
     * Check if a given number matches the number generated by the game.
     * @param number the user predicted
     * @return true if the predicted number matches the system generated number
     */
    boolean isSecretNumber(int number);
}
