package com.company;

public interface INumberGenerator {
    /**
     * Returns generated number.
     * @return int
     */
    int getSecretNumber();

    /**
     * Check if a given number matches the number generated by the game.
     * @param n
     * @return boolean
     */
    boolean isSecretNumber(int n);
}
