package com.company;

public enum Text {
    UNKNOWN_FAILURE,
    WRONG_INPUT_TYPE,
    GREETING,
    CONGRATULATION,
    HINT_NUMBER_GREATER,
    HINT_NUMBER_LESSER,
    INPUT_NUMBER,
    EXPECTED_NUMBER
}
